/**
 * Cron preset helpers for the scheduled-task form.
 *
 * Pure functions, no external deps. Cron expressions produced by presets are
 * generated by us, so we never need to parse arbitrary cron for the happy path;
 * `parseCron` only round-trips the canonical shapes we emit and falls back to
 * `custom` for anything else.
 */

import {
  displayTimeZone,
  formatTaskDateTime,
  formatTaskTime,
  type TaskTimeLabels,
} from "./format";
import type { ScheduledTask } from "./types";

export type CronPreset = "hourly" | "daily" | "weekly" | "monthly" | "custom";

export type Weekday = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export type CronParts = {
  minute?: number;
  hour?: number;
  weekdays?: Weekday[];
  dayOfMonth?: number;
  raw?: string;
};

export type ScheduleType = "once" | "cron" | "interval";

export type IntervalUnit = "seconds" | "minutes" | "hours";

export const MAX_INTERVAL_SECONDS = 30 * 24 * 60 * 60;
export const DEFAULT_INTERVAL_MIN_SECONDS = 60;

export type ScheduleFormState = {
  scheduleType: ScheduleType;
  preset?: CronPreset;
  parts?: CronParts;
  /** datetime-local wall value "YYYY-MM-DDTHH:mm", interpreted in `timezone`. */
  runAtLocal?: string;
  intervalAmount?: number;
  intervalUnit?: IntervalUnit;
  timezone: string;
};

export function intervalToSeconds(amount: number, unit: IntervalUnit): number {
  if (!Number.isInteger(amount) || amount < 1) {
    throw new Error("interval amount must be a positive integer");
  }
  if (unit === "hours") {
    return amount * 3600;
  }
  if (unit === "minutes") {
    return amount * 60;
  }
  return amount;
}

export function secondsToInterval(everySeconds: number): {
  amount: number;
  unit: IntervalUnit;
} {
  if (
    Number.isInteger(everySeconds) &&
    everySeconds >= 3600 &&
    everySeconds % 3600 === 0
  ) {
    return { amount: everySeconds / 3600, unit: "hours" };
  }
  if (
    Number.isInteger(everySeconds) &&
    everySeconds >= 60 &&
    everySeconds % 60 === 0
  ) {
    return { amount: everySeconds / 60, unit: "minutes" };
  }
  return {
    amount: Math.max(1, Math.trunc(everySeconds) || 1),
    unit: "seconds",
  };
}

export function maxIntervalAmount(unit: IntervalUnit): number {
  if (unit === "hours") {
    return MAX_INTERVAL_SECONDS / 3600;
  }
  if (unit === "minutes") {
    return MAX_INTERVAL_SECONDS / 60;
  }
  return MAX_INTERVAL_SECONDS;
}

/**
 * Smallest amount of `unit` the server accepts. `minSeconds` is the server's
 * `scheduler.min_once_delay_seconds` (`/api/features`), so a server with a
 * larger floor never lets the form submit an interval it will refuse.
 */
export function minIntervalAmount(
  unit: IntervalUnit,
  minSeconds: number = DEFAULT_INTERVAL_MIN_SECONDS,
): number {
  const floor =
    Number.isFinite(minSeconds) && minSeconds > 0
      ? minSeconds
      : DEFAULT_INTERVAL_MIN_SECONDS;
  const unitSeconds = unit === "hours" ? 3600 : unit === "minutes" ? 60 : 1;
  return Math.max(1, Math.ceil(floor / unitSeconds));
}

export function clampIntervalAmount(
  amount: number,
  unit: IntervalUnit,
  minSeconds?: number,
): number {
  const min = minIntervalAmount(unit, minSeconds);
  if (!Number.isFinite(amount)) {
    return min;
  }
  return Math.min(Math.max(min, Math.trunc(amount)), maxIntervalAmount(unit));
}

export function hasScheduleSpec(spec: {
  cron?: unknown;
  run_at?: unknown;
  every_seconds?: unknown;
}): boolean {
  if (typeof spec.cron === "string" && spec.cron.trim()) {
    return true;
  }
  if (typeof spec.run_at === "string" && spec.run_at.trim()) {
    return true;
  }
  return typeof spec.every_seconds === "number" && spec.every_seconds > 0;
}

export type ScheduleLocale = "en" | "zh";

export const WEEKDAYS: Weekday[] = [
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
  "sun",
];

const WEEKDAY_TO_CRON: Record<Weekday, string> = {
  mon: "1",
  tue: "2",
  wed: "3",
  thu: "4",
  fri: "5",
  sat: "6",
  sun: "0",
};

const CRON_TO_WEEKDAY: Record<string, Weekday> = {
  "0": "sun",
  "1": "mon",
  "2": "tue",
  "3": "wed",
  "4": "thu",
  "5": "fri",
  "6": "sat",
  "7": "sun",
};

const EN_WEEKDAY: Record<Weekday, string> = {
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  sat: "Sat",
  sun: "Sun",
};

const ZH_WEEKDAY: Record<Weekday, string> = {
  mon: "周一",
  tue: "周二",
  wed: "周三",
  thu: "周四",
  fri: "周五",
  sat: "周六",
  sun: "周日",
};

function clamp(
  value: number | undefined,
  min: number,
  max: number,
  fallback: number,
): number {
  const n =
    typeof value === "number" && Number.isFinite(value) ? value : fallback;
  return Math.max(min, Math.min(max, Math.trunc(n)));
}

export function pad2(n: number): string {
  return String(Math.trunc(Number.isFinite(n) ? n : 0)).padStart(2, "0");
}

function orderedWeekdays(days: Weekday[] | undefined): Weekday[] {
  const set = new Set(days ?? []);
  return WEEKDAYS.filter((w) => set.has(w));
}

export function serializeCron(preset: CronPreset, parts: CronParts): string {
  const m = clamp(parts.minute, 0, 59, 0);
  const h = clamp(parts.hour, 0, 23, 9);
  switch (preset) {
    case "hourly":
      return `${m} * * * *`;
    case "daily":
      return `${m} ${h} * * *`;
    case "weekly": {
      const ordered = orderedWeekdays(parts.weekdays);
      if (ordered.length === 0) {
        return `${m} ${h} * * *`;
      }
      const dow = ordered.map((w) => WEEKDAY_TO_CRON[w]).join(",");
      return `${m} ${h} * * ${dow}`;
    }
    case "monthly": {
      const dom = clamp(parts.dayOfMonth, 1, 31, 1);
      return `${m} ${h} ${dom} * *`;
    }
    case "custom":
      return (parts.raw ?? "").trim() || "0 9 * * *";
  }
  // Unreachable — the switch above is exhaustive over CronPreset.
  return (parts.raw ?? "").trim() || "0 9 * * *";
}

function isStar(field: string): boolean {
  return field === "*";
}

function isSimpleDowList(field: string): boolean {
  return field.split(",").every((tok) => /^[0-7]$/.test(tok));
}

export function parseCron(cron: string): {
  preset: CronPreset;
  parts: CronParts;
} {
  const expr = cron.trim();
  const fields = expr.split(/\s+/);
  if (fields.length !== 5) {
    return { preset: "custom", parts: { raw: expr } };
  }
  // fields.length === 5 is verified above, so every index is defined.
  const mF = fields[0]!;
  const hF = fields[1]!;
  const domF = fields[2]!;
  const monF = fields[3]!;
  const dowF = fields[4]!;
  const numMinute = /^\d+$/.test(mF);
  const numHour = /^\d+$/.test(hF);
  const numDom = /^\d+$/.test(domF);
  const stars = isStar(domF) && isStar(monF);

  // hourly: "M * * * *"
  if (numMinute && isStar(hF) && stars && isStar(dowF)) {
    return { preset: "hourly", parts: { minute: Number(mF) } };
  }
  // daily: "M H * * *"
  if (numMinute && numHour && stars && isStar(dowF)) {
    return {
      preset: "daily",
      parts: { minute: Number(mF), hour: Number(hF) },
    };
  }
  // weekly: "M H * * DOW" (simple comma list of single digits only)
  if (
    numMinute &&
    numHour &&
    isStar(domF) &&
    isStar(monF) &&
    !isStar(dowF) &&
    isSimpleDowList(dowF)
  ) {
    const parsed = dowF
      .split(",")
      .map((tok) => CRON_TO_WEEKDAY[tok])
      .filter((w): w is Weekday => Boolean(w));
    const ordered = orderedWeekdays(parsed);
    if (ordered.length > 0) {
      return {
        preset: "weekly",
        parts: { minute: Number(mF), hour: Number(hF), weekdays: ordered },
      };
    }
  }
  // monthly: "M H DOM * *"
  if (numMinute && numHour && numDom && isStar(monF) && isStar(dowF)) {
    return {
      preset: "monthly",
      parts: { minute: Number(mF), hour: Number(hF), dayOfMonth: Number(domF) },
    };
  }
  return { preset: "custom", parts: { raw: expr } };
}

export function describeSchedule(
  state: ScheduleFormState,
  locale: ScheduleLocale,
): string {
  const tz = state.timezone;
  const zh = locale === "zh";

  if (state.scheduleType === "once") {
    const runAt = (state.runAtLocal ?? "").replace("T", " ");
    return zh ? `单次 ${runAt} (${tz})` : `Once at ${runAt} (${tz})`;
  }

  if (state.scheduleType === "interval") {
    const amount = state.intervalAmount ?? 1;
    const unit = state.intervalUnit ?? "minutes";
    if (zh) {
      // "每分钟" / "每小时", never "每 1 分钟".
      if (unit === "hours") {
        return amount === 1 ? "每小时" : `每 ${amount} 小时`;
      }
      if (unit === "seconds") {
        return amount === 1 ? "每秒" : `每 ${amount} 秒`;
      }
      return amount === 1 ? "每分钟" : `每 ${amount} 分钟`;
    }
    if (unit === "hours") {
      return amount === 1 ? "Every hour" : `Every ${amount} hours`;
    }
    if (unit === "seconds") {
      return amount === 1 ? "Every second" : `Every ${amount} seconds`;
    }
    return amount === 1 ? "Every minute" : `Every ${amount} minutes`;
  }

  const parts = state.parts ?? {};
  const hhmm = `${pad2(parts.hour ?? 0)}:${pad2(parts.minute ?? 0)}`;

  switch (state.preset) {
    case "hourly": {
      const minute = parts.minute ?? 0;
      return zh
        ? `每小时第 ${minute} 分钟 (${tz})`
        : `Every hour at :${pad2(minute)} (${tz})`;
    }
    case "daily":
      return zh ? `每天 ${hhmm} (${tz})` : `Every day at ${hhmm} (${tz})`;
    case "weekly": {
      const ordered = orderedWeekdays(parts.weekdays);
      if (ordered.length === 0) {
        return zh ? `每天 ${hhmm} (${tz})` : `Every day at ${hhmm} (${tz})`;
      }
      if (zh) {
        const names = ordered.map((w) => ZH_WEEKDAY[w]).join("、");
        return `每周 ${names} ${hhmm} (${tz})`;
      }
      const names = ordered.map((w) => EN_WEEKDAY[w]).join(", ");
      return `Every ${names} at ${hhmm} (${tz})`;
    }
    case "monthly": {
      const dom = parts.dayOfMonth ?? 1;
      return zh
        ? `每月 ${dom} 日 ${hhmm} (${tz})`
        : `On day ${dom} of every month at ${hhmm} (${tz})`;
    }
    case "custom":
      return zh
        ? `自定义: ${parts.raw ?? ""} (${tz})`
        : `Custom: ${parts.raw ?? ""} (${tz})`;
  }
  // Unreachable — switch is exhaustive over CronPreset.
  return zh ? `自定义 (${tz})` : `Custom (${tz})`;
}

const MON_TO_FRI: Weekday[] = ["mon", "tue", "wed", "thu", "fri"];

/**
 * `parseCron` plus day-of-week ranges ("0 9 * * 1-5"), which agents often
 * write. Display only: the form keeps `parseCron`, so editing such a task
 * still shows the expression as custom instead of rewriting it.
 */
function parseDisplayCron(cron: string): {
  preset: CronPreset;
  parts: CronParts;
} {
  const parsed = parseCron(cron);
  if (parsed.preset !== "custom") {
    return parsed;
  }
  const fields = cron.split(/\s+/);
  const [m, h, dom, mon, dow] = fields;
  if (
    fields.length !== 5 ||
    !m ||
    !h ||
    !dow ||
    !/^\d+$/.test(m) ||
    !/^\d+$/.test(h) ||
    dom !== "*" ||
    mon !== "*" ||
    !/^[0-7](-[0-7])?(,[0-7](-[0-7])?)*$/.test(dow)
  ) {
    return parsed;
  }
  const days = new Set<Weekday>();
  for (const token of dow.split(",")) {
    const [start, end = start] = token.split("-").map(Number);
    if (start === undefined || end === undefined || end < start) {
      return parsed;
    }
    for (let day = start; day <= end; day++) {
      const weekday = CRON_TO_WEEKDAY[String(day)];
      if (weekday) days.add(weekday);
    }
  }
  return {
    preset: "weekly",
    parts: {
      minute: Number(m),
      hour: Number(h),
      weekdays: orderedWeekdays([...days]),
    },
  };
}

function isWeekdays(days: Weekday[] | undefined): boolean {
  const ordered = orderedWeekdays(days);
  return (
    ordered.length === MON_TO_FRI.length &&
    ordered.every((day, index) => day === MON_TO_FRI[index])
  );
}

export type TaskScheduleDescription = {
  /** Readable text for default views; never a cron string or the stored UTC of an interval. */
  text: string;
  /** The cron expression, for a tooltip only; null for other schedule types. */
  raw: string | null;
};

/**
 * Readable schedule of a saved task: "Weekdays at 09:00 (Asia/Shanghai)",
 * "Every 30 minutes" (intervals carry no zone), "Once, Tomorrow 09:00 (…)".
 * A cron that matches no preset reads "Custom schedule (tz)"; the expression
 * itself is returned only in `raw`. Pass `time` (the `t.scheduledTasks.time`
 * labels) to get relative days for one-time tasks; without them the time
 * reads as a plain date ("Oct 7 09:00"), never an ISO value.
 */
export function describeTaskSchedule(
  task: Pick<ScheduledTask, "schedule_type" | "schedule_spec" | "timezone">,
  locale: string,
  options: { time?: TaskTimeLabels; now?: Date } = {},
): TaskScheduleDescription {
  const lang: ScheduleLocale = locale.toLowerCase().startsWith("zh")
    ? "zh"
    : "en";
  const zh = lang === "zh";
  const spec = task.schedule_spec;
  const timezone = displayTimeZone(task);

  if (task.schedule_type === "interval") {
    const seconds =
      typeof spec.every_seconds === "number" ? spec.every_seconds : 0;
    if (Number.isInteger(seconds) && seconds > 0 && seconds % 86400 === 0) {
      // Whole days read as days ("每天", "Every 2 days"), not "每 24 小时".
      const days = seconds / 86400;
      let text = days === 1 ? "Every day" : `Every ${days} days`;
      if (zh) {
        text = days === 1 ? "每天" : `每 ${days} 天`;
      }
      return { text, raw: null };
    }
    const { amount, unit } = secondsToInterval(seconds);
    return {
      text: describeSchedule(
        {
          scheduleType: "interval",
          intervalAmount: amount,
          intervalUnit: unit,
          timezone,
        },
        lang,
      ),
      raw: null,
    };
  }

  if (task.schedule_type === "once") {
    const runAt =
      typeof spec.run_at === "string"
        ? onceRunAtInstant(spec.run_at, timezone)
        : "";
    const when = options.time
      ? formatTaskTime(runAt, {
          timeZone: timezone,
          locale,
          labels: options.time,
          now: options.now,
        })
      : formatTaskDateTime(runAt, {
          timeZone: timezone,
          locale,
          now: options.now,
        });
    return {
      text: zh ? `单次，${when} (${timezone})` : `Once, ${when} (${timezone})`,
      raw: null,
    };
  }

  const cron = typeof spec.cron === "string" ? spec.cron.trim() : "";
  const { preset, parts } = parseDisplayCron(cron);
  if (preset === "custom") {
    return {
      text: zh ? `自定义时间 (${timezone})` : `Custom schedule (${timezone})`,
      raw: cron,
    };
  }
  if (preset === "weekly" && isWeekdays(parts.weekdays)) {
    const hhmm = `${pad2(parts.hour ?? 0)}:${pad2(parts.minute ?? 0)}`;
    return {
      text: zh
        ? `工作日 ${hhmm} (${timezone})`
        : `Weekdays at ${hhmm} (${timezone})`,
      raw: cron,
    };
  }
  return {
    text: describeSchedule(
      { scheduleType: "cron", preset, parts, timezone },
      lang,
    ),
    raw: cron,
  };
}

/**
 * Convert a datetime-local wall value (interpreted in `timezone`) to a UTC ISO
 * string. The backend's `datetime.fromisoformat` treats naive strings as UTC,
 * so we must submit an explicit offset. DST-safe via Intl.
 */
export function zonedLocalToUtcIso(
  localValue: string,
  timezone: string,
): string {
  const [date, time] = localValue.split("T");
  const [y, mo, d] = (date ?? "").split("-").map(Number);
  const [h, mi] = (time ?? "00:00").split(":").map(Number);
  const refMs = Date.UTC(y ?? 1970, (mo ?? 1) - 1, d ?? 1, h ?? 0, mi ?? 0);
  // The offset at the wall-time-as-UTC instant is stale when a DST transition
  // sits between that instant and the real one (e.g. "03:30" the morning of
  // spring-forward resolves with the pre-transition offset, firing an hour
  // late and breaking the round-trip with `utcToZonedLocalInput`). Resolve
  // once, then re-derive the offset at the candidate instant; one correction
  // converges for real timezones.
  let offsetMs = tzOffsetMs(timezone, new Date(refMs));
  let utcMs = refMs - offsetMs;
  const correctedOffsetMs = tzOffsetMs(timezone, new Date(utcMs));
  if (correctedOffsetMs !== offsetMs) {
    offsetMs = correctedOffsetMs;
    utcMs = refMs - offsetMs;
  }
  const utc = new Date(utcMs);
  return `${utc.getUTCFullYear()}-${pad2(utc.getUTCMonth() + 1)}-${pad2(
    utc.getUTCDate(),
  )}T${pad2(utc.getUTCHours())}:${pad2(utc.getUTCMinutes())}:${pad2(
    utc.getUTCSeconds(),
  )}+00:00`;
}

/**
 * Inverse of `zonedLocalToUtcIso`: render a stored UTC ISO as the datetime-local
 * wall value ("YYYY-MM-DDTHH:mm") in `timezone`. Used when editing a one-time task.
 */
export function utcToZonedLocalInput(iso: string, timezone: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) {
    return "";
  }
  const offsetMs = tzOffsetMs(timezone, d);
  const local = new Date(d.getTime() + offsetMs);
  return `${local.getUTCFullYear()}-${pad2(local.getUTCMonth() + 1)}-${pad2(
    local.getUTCDate(),
  )}T${pad2(local.getUTCHours())}:${pad2(local.getUTCMinutes())}`;
}

/**
 * The instant of a one-time task's stored `run_at`. A chat-created task keeps
 * `run_at` as the agent sent it, usually a wall-clock time with no offset
 * ("2026-10-07T09:00:00") meant in the task's zone, the same way the server
 * reads it; reading it with `new Date()` would use the viewer's zone instead.
 * A value with an offset is already an instant and is returned unchanged.
 */
export function onceRunAtInstant(runAt: string, timezone: string): string {
  const value = runAt.trim();
  if (!value || /(?:Z|[+-]\d{2}(?::?\d{2})?)$/i.test(value)) {
    return value;
  }
  const local = /^(\d{4}-\d{2}-\d{2})[T ](\d{2}:\d{2})/.exec(value);
  if (!local) {
    return value;
  }
  try {
    return zonedLocalToUtcIso(`${local[1]}T${local[2]}`, timezone || "UTC");
  } catch {
    return value;
  }
}

/** Validate minute-precision YYYY-MM-DDTHH:mm input; invalid or skipped wall times return null. */
export function validZonedLocalToUtcIso(
  localValue: string,
  timezone: string,
): string | null {
  try {
    const iso = zonedLocalToUtcIso(localValue, timezone);
    return utcToZonedLocalInput(iso, timezone) === localValue ? iso : null;
  } catch {
    return null;
  }
}

/**
 * The instant of an edited wall value that started as `stored`. A
 * minute-precision wall time cannot keep seconds or name the later instant
 * of a repeated (DST fall-back) hour, so while it still shows `stored` in
 * `timezone` the stored instant is kept; otherwise it reads as
 * `validZonedLocalToUtcIso`.
 */
export function editedZonedLocalToUtcIso(
  localValue: string,
  timezone: string,
  stored: string | null | undefined,
): string | null {
  if (stored && utcToZonedLocalInput(stored, timezone) === localValue) {
    return stored;
  }
  return validZonedLocalToUtcIso(localValue, timezone);
}

function tzOffsetMs(timezone: string, date: Date): number {
  const tzParts = formatParts(timezone, date);
  const utcParts = formatParts("UTC", date);
  const tzMs = toUtcMs(tzParts);
  const utcMs = toUtcMs(utcParts);
  // >0 means the timezone wall clock is ahead of UTC (east of UTC).
  return tzMs - utcMs;
}

function formatParts(timezone: string, date: Date): Record<string, number> {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    hourCycle: "h23",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  }).formatToParts(date);
  const out: Record<string, number> = {};
  for (const p of parts) {
    out[p.type] = Number(p.value);
  }
  return out;
}

function toUtcMs(p: Record<string, number>): number {
  return Date.UTC(
    p.year ?? 1970,
    (p.month ?? 1) - 1,
    p.day ?? 1,
    p.hour ?? 0,
    p.minute ?? 0,
    p.second ?? 0,
  );
}
