const en = {
  platformTitle: "Platform provided",
  platformHint: "Shared capabilities managed through deployment configuration.",
  personalTitle: "My plugins",
  personalHint: "Your connections and settings are only used by your account.",
  install: "Configure plugin",
  name: "Connection name",
  url: "Server URL",
  authorization: "Authorization header (optional)",
  access_token: "Access token",
  sign_secret: "Robot signing secret",
  webhook_key: "Robot webhook key (the key parameter in its URL)",
  save: "Save configuration",
  accountHint:
    "This configuration is saved to your account and is only used by your runs.",
  saved: "Configuration saved",
  unknown: "Not checked",
  required: "Account required",
  configured: "Credentials configured",
  notConfigured: "Not configured",
  connected: "Account connected",
  notRequired: "No account configured",
  catalogError: "Could not load the plugin directory",
  adapterError: "Integration status unavailable",
  installed: "Configured",
  selectionTitle: "Plugins and skills",
  plugins: "MCP plugins",
  skills: "Skills (including integration skills)",
  all: "Use all enabled",
  selected: "Choose capabilities",
  unavailable: "Unavailable",
  hint: "Choose the plugins and skills this agent can use. Changes apply on the next run, including delegated tasks.",
  version: "Catalog version",
  noPlugins: "No configured plugins",
  invalidUrl: "Enter an HTTP or HTTPS server URL.",
};
const zh: typeof en = {
  platformTitle: "平台提供",
  platformHint: "由平台统一配置，供所有用户使用。",
  personalTitle: "我的插件",
  personalHint: "连接和配置仅属于你的账号，其他用户无法使用。",
  install: "配置插件",
  name: "连接名称",
  url: "服务地址",
  authorization: "授权请求头（可选）",
  access_token: "访问令牌（Access Token）",
  sign_secret: "机器人加签密钥",
  webhook_key: "机器人 Webhook 密钥（地址中的 key 参数）",
  save: "保存配置",
  accountHint: "这里的配置仅保存到你的账号，其他用户无法查看或使用。",
  saved: "配置已保存",
  unknown: "未检测",
  required: "需要连接账号",
  configured: "已配置凭据",
  notConfigured: "未配置",
  connected: "账号已连接",
  notRequired: "未配置账号",
  catalogError: "无法加载插件目录",
  adapterError: "无法获取集成状态",
  installed: "已配置",
  selectionTitle: "插件与技能",
  plugins: "MCP 插件",
  skills: "技能（包含集成技能）",
  all: "使用全部已启用能力",
  selected: "选择能力",
  unavailable: "当前不可用",
  hint: "选择此 Agent 使用的插件与技能，下次运行时生效，委派任务也会沿用。",
  version: "目录版本",
  noPlugins: "暂无已配置插件",
  invalidUrl: "请输入 HTTP 或 HTTPS 服务地址。",
};
export const capabilityCopy = (locale: string) =>
  locale === "zh-CN" ? zh : en;
